<a href="https://colab.research.google.com/github/papraba95/introdatascience/blob/master/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays:
  1. Allows severals Mathematics Operations
  2. Faster operations

In [ ]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [1+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001208235000000002


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5 # np_array + np_array + 5

end_time = process_time()

print(end_time - start_time)

0.00040311000000015085


Numpy Arrays

In [ ]:
# list

list1 = [1,2,3,4,5]

print(list1)

type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])

print(np_array)

type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8,)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Intial Placeholder in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(4) #identity matrix have equal rows and columns
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.eye(5) #identity matrix have equal rows and columns
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b) # provide random values from 0 to 1

[[0.48470028 0.22567172 0.14671986 0.81515469]
 [0.46582846 0.14484471 0.11099362 0.67396698]
 [0.46931876 0.13676418 0.55702952 0.88009408]]


In [ ]:
# random integer values array within specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[67 84 29 36 22]
 [85 70 93 26 84]
 [87 98 38 61 63]]


In [ ]:
# array of evenly spaced values ---> specifying the number of values required
d = np.linspace(10,30,5) # starting,ending point,evenly space
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[29 65 47 46 18]
 [28 31 33 58 14]
 [40 17 76 20 16]
 [20 45 81 71 53]
 [68 42 38 61 41]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimension
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of values in an array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or joint two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 3 2]
 [4 6 5]
 [4 0 9]]
[[12 15 15]
 [18 15 12]
 [14 16 14]]


In [ ]:
print(a+b) #elementwise addition
print(a - b)
print(a*b)
print(a/b)

[[19 18 17]
 [22 21 17]
 [18 16 23]]
[[ -5 -12 -13]
 [-14  -9  -7]
 [-10 -16  -5]]
[[ 84  45  30]
 [ 72  90  60]
 [ 56   0 126]]
[[0.58333333 0.2        0.13333333]
 [0.22222222 0.4        0.41666667]
 [0.28571429 0.         0.64285714]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[0 2 3]
 [2 9 9]
 [1 1 8]]
[[13 11 10]
 [17 14 15]
 [11 10 15]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 13 13]
 [19 23 24]
 [12 11 23]]
[[-13  -9  -7]
 [-15  -5  -6]
 [-10  -9  -7]]
[[  0  22  30]
 [ 34 126 135]
 [ 11  10 120]]
[[0.         0.18181818 0.3       ]
 [0.11764706 0.64285714 0.6       ]
 [0.09090909 0.1        0.53333333]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 2 5]
 [5 7 8]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 5]
 [2 7]
 [5 8]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 5 2]
 [4 6 1]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 4]
 [5 6]
 [2 1]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 4 2]
 [2 0 6]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 4]
 [2 2]
 [0 6]]
(3, 2)
